Set-Location "$env:USERPROFILE\dev\IPO_Sniper_AI_v4"

$lines = @(
'/**'
' * Volatility Edge v1 -- Decision Matrix Phase 4.'
' *'
' * Paper/recorded only. This module NEVER places an order and has NO'
' * execution authority -- see decisionMatrix/types.ts non-negotiable'
' * rule. It only produces a candidate edge layer record for later'
' * measurement.'
' *'
' * Signal: implied volatility (average IV of near-the-money contracts'
' * in the standard target DTE window) minus realized volatility'
' * (annualized stdev of daily log returns over the trailing window).'
' * This is a simple, disclosed calculation, NOT an IV rank/percentile'
' * (that would require historical IV we do not persist yet).'
' *'
' * Thresholds are heuristic and adjustable, not backtested.'
' */'
''
'import { AlpacaBarsProvider, type PriceBar } from "@/engine/evidence/providers/AlpacaBarsProvider";'
'import { AlpacaOptionsProvider } from "@/engine/trading/providers/AlpacaOptionsProvider";'
''
'export type VolatilityEdgeDecision = "iv_rich" | "iv_cheap" | "no_edge";'
''
'export interface VolatilityEdgeResult {'
'    ticker: string;'
'    decision: VolatilityEdgeDecision;'
'    status: "PASS" | "FAIL" | "NOT_EVALUATED";'
'    reasonCode: string;'
'    realizedVolPercent: