/**
 * Real compliance disclosures, not filler copy. Built in response to
 * a direct request to address: (1) Anthropic's Usage Policy treating
 * financial advice as a High-Risk Use Case requiring AI-use
 * disclosure, (2) SEC "AI washing" enforcement scrutiny of whether
 * AI-related marketing claims match what a product actually does,
 * (3) the standing "not a registered investment adviser" positioning
 * this whole session has been building toward.
 *
 * This is NOT a substitute for real legal review — see the note in
 * chat. It's a real, honest first pass at the disclosures a lawyer
 * would expect to already exist before reviewing anything further.
 */
export default function Disclosures() {
    return (
        <section id="disclosures" className="border-t border-zinc-900 bg-zinc-950 px-6 py-16 text-white">
            <div className="mx-auto max-w-3xl space-y-6 text-sm text-zinc-400">

                <h2 className="text-lg font-semibold text-zinc-200">Important Disclosures</h2>

                <div>
                    <h3 className="mb-1 font-medium text-zinc-300">Not Investment Advice</h3>
                    <p>
                        IPO Sniper AI is a research tool. It does not provide investment, legal, or tax advice,
                        and nothing on this platform is a recommendation to buy, sell, or hold any security.
                        It is built to help you gather and evaluate evidence for your own decisions — not to
                        make those decisions for you. Consult a licensed financial advisor before acting on
                        anything you see here.
                    </p>
                </div>

                <div>
                    <h3 className="mb-1 font-medium text-zinc-300">Not a Registered Investment Adviser</h3>
                    <p>
                        IPO Sniper AI and its operator are not a registered investment adviser, broker-dealer,
                        or licensed financial services provider. This platform is offered for informational and
                        research purposes only.
                    </p>
                </div>

                <div>
                    <h3 className="mb-1 font-medium text-zinc-300">Use of AI</h3>
                    <p>
                        Company scores, recommendations, and confidence levels are computed by deterministic
                        rules applied to verified evidence — not generated by AI. A separate, clearly-labeled
                        Executive Summary section on each report is written by an AI model, constrained to only
                        describe the already-computed findings above it — it does not decide the recommendation
                        or introduce new claims. Where this AI-generated text appears, it&apos;s marked as such
                        on the report itself.
                    </p>
                </div>

                <div>
                    <h3 className="mb-1 font-medium text-zinc-300">Data Accuracy &amp; Completeness</h3>
                    <p>
                        Data is sourced from third-party providers (SEC EDGAR, Finnhub, and others) and may be
                        incomplete, delayed, or contain errors outside our control. Every report shows exactly
                        how much of its underlying evidence is verified — treat unverified fields as unknown,
                        not as zero or negative. Verify anything material independently before acting on it.
                    </p>
                    <p className="mt-2">
                        Institutional/13F holdings data specifically reflects each manager&apos;s last required
                        SEC disclosure, which can be filed up to 45 days after the end of the quarter it
                        describes — meaning a position shown here may already be materially different from
                        that manager&apos;s current, real holdings. ARK Invest holdings shown on this platform
                        are more current (ARK discloses daily), but every other named-investor holding is on
                        this quarterly, lagged basis unless stated otherwise.
                    </p>
                </div>

                <div>
                    <h3 className="mb-1 font-medium text-zinc-300">Risk</h3>
                    <p>
                        Investing involves risk, including possible loss of principal. Historical conviction
                        scores or past analysis are not indicative of future results.
                    </p>
                </div>

                <div className="flex gap-4 border-t border-zinc-900 pt-4 text-xs">
                    <a href="/terms" className="underline hover:text-zinc-300">Terms of Service</a>
                    <a href="/privacy" className="underline hover:text-zinc-300">Privacy Policy</a>
                </div>

            </div>
        </section>
    );
}
